services:
  postgres:
    image: postgres:17
    container_name: teamflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: teamflow
      POSTGRES_PASSWORD: teamflow
      POSTGRES_DB: postgres
    ports:
      - '5434:5432'
    volumes:
      - teamflow_postgres_data:/var/lib/postgresql/data

volumes:
  teamflow_postgres_data:
